stages:
  - lint
  - test
  - name: release
    if: branch = master

node_js_defaults: &node_js_defaults
  language: node_js
  node_js: '11'
  cache:
    yarn: true
    directories:
      - node_modules

jobs:
  include:
    - stage: lint
      <<: *node_js_defaults
      script:
        - yarn typecheck
        - yarn lint:check

    - stage: test
      <<: *node_js_defaults
      script: yarn test:ci

    - stage: release
      <<: *node_js_defaults
      script: yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
