[build]
  # The directory to look for package.json, .nvmrc, etc.
  base = ""
  # Build output directory.
  publish = "storybookDist"
  # Command to build the files.
  command = "yarn build-storybook"

  environment = { NODE_ENV = "production" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.develop]
  environment = { NODE_ENV = "production" }
